# Generated by Django 3.2.15 on 2022-10-01 08:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=155, verbose_name='')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Summer', 'Лето'), ('Winter', 'Зима'), ('Spring', 'Весна'), ('Autumn', 'Осень')], max_length=9, verbose_name='Сезон')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='post/', verbose_name='Изображение')),
                ('ingredients', ckeditor.fields.RichTextField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_preparing', models.CharField(max_length=10, verbose_name='Время приготовления')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='PostStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название шага')),
                ('text', models.TextField(verbose_name='Текс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_step/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тег')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_view', to='food.post', verbose_name='Пост')),
            ],
        ),
    ]
