# Generated by Django 3.2.15 on 2022-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritepost',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='favorite_user', to='food.FavoritePost', verbose_name='Добавившие в избранное'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='post_favorite', to='food.FavoritePost', verbose_name='Добавившие в избранное'),
        ),
    ]
