# Generated by Django 3.2.15 on 2022-10-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20221001_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='food.post')),
                ('season', models.CharField(choices=[('Summer', 'Лето'), ('Winter', 'Зима'), ('Spring', 'Весна'), ('Autumn', 'Осень')], max_length=9, verbose_name='Сезон')),
            ],
            bases=('food.post',),
        ),
        migrations.RemoveField(
            model_name='favoritepost',
            name='season',
        ),
    ]
