# Generated by Django 3.2.15 on 2022-10-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20221001_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepost',
            name='post',
        ),
    ]
