# Generated by Django 3.2.15 on 2022-10-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_favoritepost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritepost',
            name='user',
        ),
        migrations.AddField(
            model_name='favoritepost',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to='food.favoritepost', verbose_name='Добавившие в избранное'),
            preserve_default=False,
        ),
    ]
