# Generated by Django 3.2.15 on 2022-10-01 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0009_remove_favoritepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='post_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Добавившие в избранное'),
        ),
        migrations.DeleteModel(
            name='FavoritePost',
        ),
    ]
