# Generated by Django 3.2.15 on 2022-10-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_post_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
