# Generated by Django 4.1.1 on 2022-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststep',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
