# Generated by Django 4.1.1 on 2022-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_alter_poststep_options_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='poststep',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название шага'),
        ),
    ]
