# Generated by Django 4.1.1 on 2022-10-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_post_is_main_category_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_create',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
